# Shared UI strings for the Bibli server scripts. The language follows the
# Windows display language (Get-UICulture); anything other than nl or en falls
# back to French, the reference (CLAUDE.md), suited to FWB organisations. Only strings
# a volunteer sees are translated — code, comments and bibli.exe's logs stay
# English. Single-quoted here, so an apostrophe is doubled ('').
function Get-BibliStrings {
  $lang = (Get-UICulture).TwoLetterISOLanguageName
  if ($lang -ne 'nl' -and $lang -ne 'en') { $lang = 'fr' }
  $all = @{
    fr = @{
      tagline      = 'Gestion de bibliothèque pour les petites structures'
      version      = 'Version {0}'
      intro        = 'Bibli gère le catalogue, les lecteurs et les prêts d''une petite bibliothèque : école, centre culturel, maison de repos, hôpital… Les données restent sur vos ordinateurs.'
      role_prompt  = 'Comment utiliser Bibli sur ce PC ?'
      role_app_title    = 'Seulement sur ce PC'
      role_app_note     = 'Bibli s''ouvre dans sa propre fenêtre et s''arrête quand on la ferme. Aucun droit d''administrateur nécessaire.'
      role_server_title = 'Serveur pour plusieurs appareils'
      role_server_note  = 'Tourne en permanence et démarre avec le PC ; les tablettes et les autres postes du réseau s''y connectent. Demande un compte administrateur.'
      role_client_title = 'Autre poste'
      role_client_note  = 'Pose seulement un raccourci vers le serveur Bibli déjà installé sur un autre PC.'
      about        = 'Logiciel libre sous licence AGPL-3.0, par {0} et ses contributeurs.'
      lk_guide = 'Guide d''installation'; lk_changes = 'Nouveautés'; lk_source = 'Code source'; lk_licence = 'Licence'
      ok = 'OK'; cancel = 'Annuler'; close = 'Fermer'; quit = 'Quitter'
      adm_heading  = 'Droits d''administrateur nécessaires'
      adm_why      = 'Installer Bibli comme serveur demande un compte administrateur de ce PC. Windows n''a pas accordé cette autorisation : la demande a été refusée ou annulée, ou ce compte n''est pas administrateur. Rien n''a été installé.'
      adm_how      = 'Pour installer le serveur :'
      adm_step1    = '1. Fermez cette fenêtre, faites un clic droit sur le fichier téléchargé « {0} » et choisissez « Exécuter en tant qu''administrateur ».'
      adm_step2    = '2. Si Windows demande un nom et un mot de passe, ce sont ceux d''un compte administrateur : demandez-les à la personne qui gère ce PC.'
      adm_show     = 'Montrer le fichier dans l''Explorateur'
      adm_alt      = 'Sans compte administrateur, choisissez « Seulement sur ce PC » : Bibli fonctionne alors sur cet ordinateur uniquement.'
      adm_retry    = 'Réessayer'
      up_saved     = 'Copie de la base avant mise à jour : {0}'
      press_enter  = 'Appuyez sur Entrée pour fermer…'
      yes = 'oui'; no = 'non'
      pw_heading   = 'Mot de passe de la bibliothèque'
      pw_prompt    = 'Choisissez le mot de passe de la bibliothèque (au moins 12 caractères ; une phrase de trois ou quatre mots convient). Il sera demandé pour se connecter.'
      pw_prompt_app = 'Premier lancement : choisissez le mot de passe de la bibliothèque. Il sera demandé pour se connecter.'
      pw_label = 'Mot de passe'; pw_confirm = 'Confirmez le mot de passe'; pw_show = 'Afficher le mot de passe'
      pw_tooshort  = 'Au moins {0} caractères.'
      pw_empty     = 'Le mot de passe ne peut pas être vide.'
      pw_mismatch  = 'Les deux mots de passe ne sont pas identiques.'
      st_stop = 'Arrêt du serveur et copie de sécurité de la base…'; st_files = 'Copie des fichiers du programme…'
      st_data = 'Préparation du dossier des données…'; st_service = 'Configuration du service Windows…'
      st_network = 'Réglage du pare-feu et de la mise en veille…'; st_shortcuts = 'Création des raccourcis…'
      st_start = 'Démarrage du serveur…'
      app_nostart = 'Bibli n''a pas pu démarrer. Voir {0}'
      installing   = 'Installation de Bibli dans {0} (données dans {1})…'
      cancelled    = 'Annulé.'
      sum_heading  = 'Bibli est installé'
      sum_running  = 'Le serveur tourne et démarrera tout seul à chaque allumage du PC.'
      sum_thispc   = 'Sur ce PC :'
      sum_others   = 'Sur les tablettes et les autres postes :'
      sum_ip_hint  = 'Les tablettes Android et les iPad ne reconnaissent souvent pas le nom du PC : donnez-leur l''adresse IP.'
      sum_where    = 'Icône « Bibli » sur le Bureau et dans la zone de notification. Le menu Démarrer › « Bibli (serveur) » sert à démarrer, arrêter, mettre à jour ou désinstaller ; Bibli figure aussi dans Paramètres › Applications.'
      sum_open     = 'Ouvrir Bibli'
      sum_notup    = 'Bibli n''a pas encore répondu. Voir {0}'
      menu_folder  = 'Bibli (serveur)'
      svc_desc     = 'Serveur de la bibliothèque (Bibli).'
      sc_open = 'Ouvrir Bibli'; sc_address = 'Adresse pour les tablettes'; sc_status = 'État du serveur'
      sc_start = 'Démarrer le serveur'; sc_stop = 'Arrêter le serveur'; sc_restart = 'Redémarrer le serveur'
      sc_autostart = 'Démarrage automatique'; sc_tray = 'Afficher l''icône de notification'
      sc_logs = 'Voir le journal'; sc_data = 'Dossier des données'; sc_update = 'Mettre à jour Bibli'; sc_uninstall = 'Désinstaller Bibli'
      msg_started = 'Serveur démarré.'; msg_stopped = 'Serveur arrêté.'; msg_restarted = 'Serveur redémarré.'
      lbl_autostart = 'Démarre avec le PC :'; lbl_task = 'Service :'; lbl_responds = 'Répond sur le réseau :'; lbl_address = 'Adresse :'
      addr_intro = 'Sur les tablettes et les autres ordinateurs, ouvrir :'
      t_hide = 'Cacher l''icône (le serveur continue)'
      t_hidden = 'L''icône ne s''affichera plus à l''ouverture de session ; le serveur continue de tourner. Pour la retrouver : menu Démarrer › Bibli (serveur) › Afficher l''icône de notification.'
      t_autostart = 'Démarrer le serveur avec le PC'
      as_on_q  = 'Le serveur ne démarre pas avec le PC. Le faire démarrer automatiquement à chaque allumage ?'
      as_off_q = 'Le serveur démarre à chaque allumage du PC. Ne plus le démarrer automatiquement ? Il faudra alors le démarrer à la main (menu Bibli (serveur) › Démarrer le serveur), et les tablettes n''y auront pas accès avant.'
      msg_auto_on = 'Le serveur démarrera avec le PC.'; msg_auto_off = 'Le serveur ne démarrera plus avec le PC.'
      tip_up = 'Bibli — en marche'; tip_down = 'Bibli — arrêté'
      up_title = 'Choisir le nouveau Bibli téléchargé (.exe)'
      un_heading = 'Désinstaller Bibli ?'
      un_what_server = 'Le service Windows, son démarrage automatique, l''icône de notification, les raccourcis et le programme seront supprimés. Les tablettes et les autres postes n''auront plus accès à Bibli.'
      un_what_app = 'Le programme et ses raccourcis seront supprimés.'
      un_keep  = 'Les données de la bibliothèque (livres, lecteurs, prêts, sauvegardes) restent dans {0} : réinstaller Bibli les retrouve.'
      un_purge = 'Supprimer aussi toutes les données de la bibliothèque (irréversible)'
      un_purge_confirm = 'Toutes les données de la bibliothèque seront effacées définitivement, sauvegardes comprises. Continuer ?'
      un_go = 'Désinstaller'
      un_needadmin = 'Désinstaller le serveur demande un compte administrateur de ce PC, et Windows n''a pas accordé l''autorisation. Rien n''a été supprimé. Réessayez avec un compte administrateur.'
      un_kept = 'Bibli a été supprimé. Les données de la bibliothèque sont conservées dans {0}'
      un_all = 'Bibli et toutes ses données ont été supprimés.'
      cl_prompt = 'Nom ou adresse IP du serveur Bibli (ex. BIBLIO-PC)'
      cl_done = 'Raccourci « Bibli » créé sur le Bureau. Il ouvre {0}'
    }
    nl = @{
      tagline      = 'Bibliotheekbeheer voor kleine organisaties'
      version      = 'Versie {0}'
      intro        = 'Bibli beheert de catalogus, de lezers en de uitleningen van een kleine bibliotheek: school, cultureel centrum, woonzorgcentrum, ziekenhuis… De gegevens blijven op uw eigen computers.'
      role_prompt  = 'Hoe Bibli op deze pc gebruiken?'
      role_app_title    = 'Alleen op deze pc'
      role_app_note     = 'Bibli opent in een eigen venster en stopt wanneer u het sluit. Geen beheerdersrechten nodig.'
      role_server_title = 'Server voor meerdere toestellen'
      role_server_note  = 'Draait altijd en start mee met de pc; tablets en andere computers op het netwerk maken er verbinding mee. Vraagt een beheerdersaccount.'
      role_client_title = 'Andere computer'
      role_client_note  = 'Maakt alleen een snelkoppeling naar de Bibli-server die al op een andere pc draait.'
      about        = 'Vrije software onder de AGPL-3.0-licentie, door {0} en de bijdragers.'
      lk_guide = 'Installatiegids'; lk_changes = 'Nieuw in deze versie'; lk_source = 'Broncode'; lk_licence = 'Licentie'
      ok = 'OK'; cancel = 'Annuleren'; close = 'Sluiten'; quit = 'Afsluiten'
      adm_heading  = 'Beheerdersrechten nodig'
      adm_why      = 'Bibli als server installeren vraagt een beheerdersaccount van deze pc. Windows heeft die toestemming niet gegeven: de vraag werd geweigerd of geannuleerd, of dit account is geen beheerder. Er is niets geïnstalleerd.'
      adm_how      = 'Om de server te installeren:'
      adm_step1    = '1. Sluit dit venster, klik met de rechtermuisknop op het gedownloade bestand « {0} » en kies « Als administrator uitvoeren ».'
      adm_step2    = '2. Vraagt Windows een naam en wachtwoord, dan zijn dat die van een beheerdersaccount: vraag ze aan wie deze pc beheert.'
      adm_show     = 'Het bestand tonen in Verkenner'
      adm_alt      = 'Zonder beheerdersaccount kiest u « Alleen op deze pc »: Bibli werkt dan alleen op deze computer.'
      adm_retry    = 'Opnieuw proberen'
      up_saved     = 'Kopie van de database vóór de update: {0}'
      press_enter  = 'Druk op Enter om te sluiten…'
      yes = 'ja'; no = 'nee'
      pw_heading   = 'Wachtwoord van de bibliotheek'
      pw_prompt    = 'Kies het wachtwoord van de bibliotheek (minstens 12 tekens; een zin van drie of vier woorden volstaat). Het wordt gevraagd om aan te melden.'
      pw_prompt_app = 'Eerste start: kies het wachtwoord van de bibliotheek. Het wordt gevraagd om aan te melden.'
      pw_label = 'Wachtwoord'; pw_confirm = 'Bevestig het wachtwoord'; pw_show = 'Wachtwoord tonen'
      pw_tooshort  = 'Minstens {0} tekens.'
      pw_empty     = 'Het wachtwoord mag niet leeg zijn.'
      pw_mismatch  = 'De twee wachtwoorden zijn niet gelijk.'
      st_stop = 'Server stoppen en de database veiligstellen…'; st_files = 'Programmabestanden kopiëren…'
      st_data = 'Gegevensmap voorbereiden…'; st_service = 'Windows-dienst instellen…'
      st_network = 'Firewall en slaapstand instellen…'; st_shortcuts = 'Snelkoppelingen maken…'
      st_start = 'Server starten…'
      app_nostart = 'Bibli kon niet starten. Zie {0}'
      installing   = 'Bibli wordt geïnstalleerd in {0} (gegevens in {1})…'
      cancelled    = 'Geannuleerd.'
      sum_heading  = 'Bibli is geïnstalleerd'
      sum_running  = 'De server draait en start voortaan vanzelf bij elke start van de pc.'
      sum_thispc   = 'Op deze pc:'
      sum_others   = 'Op de tablets en de andere computers:'
      sum_ip_hint  = 'Android-tablets en iPads herkennen de naam van de pc vaak niet: geef hun het IP-adres.'
      sum_where    = 'Pictogram « Bibli » op het bureaublad en in het systeemvak. Met het menu Start › « Bibli (server) » start, stopt, werkt u bij of verwijdert u Bibli; het staat ook in Instellingen › Apps.'
      sum_open     = 'Bibli openen'
      sum_notup    = 'Bibli heeft nog niet geantwoord. Zie {0}'
      menu_folder  = 'Bibli (server)'
      svc_desc     = 'Server van de bibliotheek (Bibli).'
      sc_open = 'Bibli openen'; sc_address = 'Adres voor tablets'; sc_status = 'Status van de server'
      sc_start = 'Server starten'; sc_stop = 'Server stoppen'; sc_restart = 'Server herstarten'
      sc_autostart = 'Automatisch starten'; sc_tray = 'Pictogram in het systeemvak tonen'
      sc_logs = 'Logboek bekijken'; sc_data = 'Gegevensmap'; sc_update = 'Bibli bijwerken'; sc_uninstall = 'Bibli verwijderen'
      msg_started = 'Server gestart.'; msg_stopped = 'Server gestopt.'; msg_restarted = 'Server herstart.'
      lbl_autostart = 'Start mee met de pc:'; lbl_task = 'Dienst:'; lbl_responds = 'Antwoordt op het netwerk:'; lbl_address = 'Adres:'
      addr_intro = 'Open op de tablets en de andere computers:'
      t_hide = 'Pictogram verbergen (server blijft draaien)'
      t_hidden = 'Het pictogram verschijnt niet meer bij het aanmelden; de server blijft draaien. Terughalen: menu Start › Bibli (server) › Pictogram in het systeemvak tonen.'
      t_autostart = 'Server starten met de pc'
      as_on_q  = 'De server start niet mee met de pc. Automatisch laten starten bij elke start van de pc?'
      as_off_q = 'De server start bij elke start van de pc. Niet meer automatisch starten? U moet hem dan zelf starten (menu Bibli (server) › Server starten), en tot dan kunnen de tablets er niet bij.'
      msg_auto_on = 'De server start mee met de pc.'; msg_auto_off = 'De server start niet meer mee met de pc.'
      tip_up = 'Bibli — actief'; tip_down = 'Bibli — gestopt'
      up_title = 'Kies de nieuwe gedownloade Bibli (.exe)'
      un_heading = 'Bibli verwijderen?'
      un_what_server = 'De Windows-dienst, het automatisch starten, het pictogram in het systeemvak, de snelkoppelingen en het programma worden verwijderd. Tablets en andere computers kunnen Bibli dan niet meer bereiken.'
      un_what_app = 'Het programma en de snelkoppelingen worden verwijderd.'
      un_keep  = 'De bibliotheekgegevens (boeken, lezers, uitleningen, back-ups) blijven in {0}: wie Bibli opnieuw installeert, vindt ze terug.'
      un_purge = 'Ook alle bibliotheekgegevens verwijderen (onomkeerbaar)'
      un_purge_confirm = 'Alle bibliotheekgegevens worden definitief gewist, back-ups inbegrepen. Doorgaan?'
      un_go = 'Verwijderen'
      un_needadmin = 'De server verwijderen vraagt een beheerdersaccount van deze pc, en Windows heeft die toestemming niet gegeven. Er is niets verwijderd. Probeer opnieuw met een beheerdersaccount.'
      un_kept = 'Bibli is verwijderd. De bibliotheekgegevens blijven bewaard in {0}'
      un_all = 'Bibli en al zijn gegevens zijn verwijderd.'
      cl_prompt = 'Naam of IP-adres van de Bibli-server (bv. BIBLIO-PC)'
      cl_done = 'Snelkoppeling « Bibli » op het bureaublad gemaakt. Opent {0}'
    }
    en = @{
      tagline      = 'Library management for small organisations'
      version      = 'Version {0}'
      intro        = 'Bibli manages the catalogue, the readers and the loans of a small library: school, cultural centre, care home, hospital… The data stays on your own computers.'
      role_prompt  = 'How will this PC use Bibli?'
      role_app_title    = 'On this PC only'
      role_app_note     = 'Bibli opens in its own window and stops when you close it. No administrator rights needed.'
      role_server_title = 'Server for several devices'
      role_server_note  = 'Always running, starts with the PC; tablets and other computers on the network connect to it. Needs an administrator account.'
      role_client_title = 'Another computer'
      role_client_note  = 'Only adds a shortcut to the Bibli server already installed on another PC.'
      about        = 'Free software under the AGPL-3.0 licence, by {0} and contributors.'
      lk_guide = 'Installation guide'; lk_changes = 'What''s new'; lk_source = 'Source code'; lk_licence = 'Licence'
      ok = 'OK'; cancel = 'Cancel'; close = 'Close'; quit = 'Quit'
      adm_heading  = 'Administrator rights needed'
      adm_why      = 'Installing Bibli as a server needs an administrator account on this PC. Windows did not grant it: the request was declined or cancelled, or this account is not an administrator. Nothing was installed.'
      adm_how      = 'To install the server:'
      adm_step1    = '1. Close this window, right-click the downloaded file "{0}" and choose "Run as administrator".'
      adm_step2    = '2. If Windows asks for a name and password, they are those of an administrator account: ask whoever manages this PC.'
      adm_show     = 'Show the file in File Explorer'
      adm_alt      = 'Without an administrator account, choose "On this PC only": Bibli then works on this computer alone.'
      adm_retry    = 'Try again'
      up_saved     = 'Copy of the database before the update: {0}'
      press_enter  = 'Press Enter to close…'
      yes = 'yes'; no = 'no'
      pw_heading   = 'Library password'
      pw_prompt    = 'Choose the library password (at least 12 characters; a phrase of three or four words works well). It will be asked to log in.'
      pw_prompt_app = 'First launch: choose the library password. It will be asked to log in.'
      pw_label = 'Password'; pw_confirm = 'Confirm the password'; pw_show = 'Show the password'
      pw_tooshort  = 'At least {0} characters.'
      pw_empty     = 'The password cannot be empty.'
      pw_mismatch  = 'The two passwords do not match.'
      st_stop = 'Stopping the server and saving a copy of the database…'; st_files = 'Copying the program files…'
      st_data = 'Preparing the data folder…'; st_service = 'Setting up the Windows service…'
      st_network = 'Setting up the firewall and sleep mode…'; st_shortcuts = 'Creating the shortcuts…'
      st_start = 'Starting the server…'
      app_nostart = 'Bibli could not start. See {0}'
      installing   = 'Installing Bibli to {0} (data in {1})…'
      cancelled    = 'Cancelled.'
      sum_heading  = 'Bibli is installed'
      sum_running  = 'The server is running and will start by itself every time the PC powers on.'
      sum_thispc   = 'On this PC:'
      sum_others   = 'On the tablets and the other computers:'
      sum_ip_hint  = 'Android tablets and iPads often do not recognise the PC''s name: give them the IP address.'
      sum_where    = 'A "Bibli" icon on the Desktop and in the notification area. The Start menu > "Bibli (server)" starts, stops, updates or uninstalls it; Bibli is also listed in Settings > Apps.'
      sum_open     = 'Open Bibli'
      sum_notup    = 'Bibli has not answered yet. See {0}'
      menu_folder  = 'Bibli (server)'
      svc_desc     = 'Library server (Bibli).'
      sc_open = 'Open Bibli'; sc_address = 'Address for tablets'; sc_status = 'Server status'
      sc_start = 'Start the server'; sc_stop = 'Stop the server'; sc_restart = 'Restart the server'
      sc_autostart = 'Automatic start'; sc_tray = 'Show the notification icon'
      sc_logs = 'View the log'; sc_data = 'Data folder'; sc_update = 'Update Bibli'; sc_uninstall = 'Uninstall Bibli'
      msg_started = 'Server started.'; msg_stopped = 'Server stopped.'; msg_restarted = 'Server restarted.'
      lbl_autostart = 'Starts with the PC:'; lbl_task = 'Service:'; lbl_responds = 'Answers on the network:'; lbl_address = 'Address:'
      addr_intro = 'On the tablets and the other computers, open:'
      t_hide = 'Hide the icon (the server keeps running)'
      t_hidden = 'The icon will no longer appear at sign-in; the server keeps running. To bring it back: Start menu > Bibli (server) > Show the notification icon.'
      t_autostart = 'Start the server with the PC'
      as_on_q  = 'The server does not start with the PC. Start it automatically every time the PC powers on?'
      as_off_q = 'The server starts every time the PC powers on. Stop starting it automatically? It will then have to be started by hand (menu Bibli (server) > Start the server), and the tablets cannot reach it until then.'
      msg_auto_on = 'The server will start with the PC.'; msg_auto_off = 'The server will no longer start with the PC.'
      tip_up = 'Bibli — running'; tip_down = 'Bibli — stopped'
      up_title = 'Choose the newly downloaded Bibli (.exe)'
      un_heading = 'Uninstall Bibli?'
      un_what_server = 'The Windows service, its automatic start, the notification icon, the shortcuts and the program will be removed. Tablets and other computers will no longer reach Bibli.'
      un_what_app = 'The program and its shortcuts will be removed.'
      un_keep  = 'The library data (books, readers, loans, backups) stays in {0}: reinstalling Bibli finds it again.'
      un_purge = 'Also delete all the library data (cannot be undone)'
      un_purge_confirm = 'All the library data will be erased for good, backups included. Continue?'
      un_go = 'Uninstall'
      un_needadmin = 'Uninstalling the server needs an administrator account on this PC, and Windows did not grant it. Nothing was removed. Try again with an administrator account.'
      un_kept = 'Bibli has been removed. The library data is kept in {0}'
      un_all = 'Bibli and all its data have been removed.'
      cl_prompt = 'Name or IP address of the Bibli server (e.g. BIBLIO-PC)'
      cl_done = '"Bibli" shortcut created on the Desktop. It opens {0}'
    }
  }
  return $all[$lang]
}
