# Shared UI strings for the Bibli server scripts. The language follows the
# Windows display language (Get-UICulture); anything other than nl or en falls
# back to French, the reference (CLAUDE.md), suited to FWB schools. Only strings
# a volunteer sees are translated — code, comments and bibli.exe's logs stay
# English. Single-quoted here, so an apostrophe is doubled ('').
function Get-BibliStrings {
  $lang = (Get-UICulture).TwoLetterISOLanguageName
  if ($lang -ne 'nl' -and $lang -ne 'en') { $lang = 'fr' }
  $all = @{
    fr = @{
      role_prompt  = 'Comment utiliser Bibli sur ce PC ?'
      role_app     = 'Seulement sur ce PC (Bibli s''ouvre dans sa fenêtre et s''arrête avec elle)'
      role_server  = 'Serveur pour plusieurs appareils (tourne en permanence, demande d''être administrateur)'
      role_client  = 'Autre poste : un raccourci vers le serveur déjà installé ailleurs'
      elevated     = 'Windows demande l''autorisation d''administrateur ; l''installation continue dans une autre fenêtre…'
      up_saved     = 'Copie de la base avant mise à jour : {0}'
      done_enter   = 'Terminé. Appuyez sur Entrée pour fermer'
      press_enter  = 'Appuyez sur Entrée pour fermer…'
      yes = 'oui'; no = 'non'
      pw_prompt    = 'Choisissez le mot de passe de la bibliothèque (au moins 12 caractères ; une phrase de trois ou quatre mots convient). Il sera demandé pour se connecter.'
      pw_tooshort  = 'Au moins 12 caractères.'
      installing   = 'Installation de Bibli dans {0} (données dans {1})…'
      cancelled    = 'Annulé.'
      sum_running  = 'Bibli est installé et démarre maintenant à chaque allumage du PC.'
      sum_thispc   = '  Sur ce PC            : {0}'
      sum_others   = '  Tablettes, autres PC : {0}'
      sum_icons1   = 'Icône « Bibli » sur le Bureau, icône dans la zone de notification, et'
      sum_icons2   = 'menu « Bibli (serveur) » dans Démarrer (démarrer / arrêter / mettre à jour).'
      sum_notup    = 'Bibli n''a pas encore répondu. Voir {0}'
      menu_folder  = 'Bibli (serveur)'
      svc_desc     = 'Serveur de la bibliothèque (Bibli).'
      sc_open = 'Ouvrir Bibli'; sc_address = 'Adresse pour les tablettes'; sc_status = 'État du serveur'
      sc_start = 'Démarrer le serveur'; sc_stop = 'Arrêter le serveur'; sc_restart = 'Redémarrer le serveur'
      sc_logs = 'Voir le journal'; sc_data = 'Dossier des données'; sc_update = 'Mettre à jour Bibli'; sc_uninstall = 'Désinstaller Bibli'
      msg_started = 'Serveur démarré.'; msg_stopped = 'Serveur arrêté.'; msg_restarted = 'Serveur redémarré.'
      lbl_task = 'Service :'; lbl_responds = 'Répond sur le réseau :'; lbl_address = 'Adresse :'
      addr_intro = 'Sur les tablettes et les autres ordinateurs, ouvrir :'
      t_hide = 'Cacher l''icône (le serveur continue)'
      tip_up = 'Bibli — en marche'; tip_down = 'Bibli — arrêté'
      up_title = 'Choisir le nouveau Bibli téléchargé (.exe)'
      un_kept = 'Bibli a été supprimé. Les données de la bibliothèque sont conservées dans {0}'
      un_all = 'Bibli et toutes ses données ont été supprimés.'
      cl_prompt = 'Nom ou adresse IP du serveur Bibli (ex. BIBLIO-PC)'
      cl_done = 'Raccourci « Bibli » créé sur le Bureau. Il ouvre {0}'
    }
    nl = @{
      role_prompt  = 'Hoe Bibli op deze pc gebruiken?'
      role_app     = 'Alleen op deze pc (Bibli opent in een eigen venster en stopt ermee)'
      role_server  = 'Server voor meerdere toestellen (draait altijd, vraagt beheerdersrechten)'
      role_client  = 'Andere computer: een snelkoppeling naar de server die elders draait'
      elevated     = 'Windows vraagt beheerdersrechten; de installatie gaat verder in een ander venster…'
      up_saved     = 'Kopie van de database vóór de update: {0}'
      done_enter   = 'Klaar. Druk op Enter om te sluiten'
      press_enter  = 'Druk op Enter om te sluiten…'
      yes = 'ja'; no = 'nee'
      pw_prompt    = 'Kies het wachtwoord van de bibliotheek (minstens 12 tekens; een zin van drie of vier woorden volstaat). Het wordt gevraagd om aan te melden.'
      pw_tooshort  = 'Minstens 12 tekens.'
      installing   = 'Bibli wordt geïnstalleerd in {0} (gegevens in {1})…'
      cancelled    = 'Geannuleerd.'
      sum_running  = 'Bibli is geïnstalleerd en start voortaan bij elke start van de pc.'
      sum_thispc   = '  Op deze pc           : {0}'
      sum_others   = '  Tablets, andere pc''s : {0}'
      sum_icons1   = 'Pictogram « Bibli » op het bureaublad, pictogram in het systeemvak, en'
      sum_icons2   = 'menu « Bibli (server) » in Start (starten / stoppen / bijwerken).'
      sum_notup    = 'Bibli heeft nog niet geantwoord. Zie {0}'
      menu_folder  = 'Bibli (server)'
      svc_desc     = 'Server van de bibliotheek (Bibli).'
      sc_open = 'Bibli openen'; sc_address = 'Adres voor tablets'; sc_status = 'Status van de server'
      sc_start = 'Server starten'; sc_stop = 'Server stoppen'; sc_restart = 'Server herstarten'
      sc_logs = 'Logboek bekijken'; sc_data = 'Gegevensmap'; sc_update = 'Bibli bijwerken'; sc_uninstall = 'Bibli verwijderen'
      msg_started = 'Server gestart.'; msg_stopped = 'Server gestopt.'; msg_restarted = 'Server herstart.'
      lbl_task = 'Dienst:'; lbl_responds = 'Antwoordt op het netwerk:'; lbl_address = 'Adres:'
      addr_intro = 'Open op de tablets en de andere computers:'
      t_hide = 'Pictogram verbergen (server blijft draaien)'
      tip_up = 'Bibli — actief'; tip_down = 'Bibli — gestopt'
      up_title = 'Kies de nieuwe gedownloade Bibli (.exe)'
      un_kept = 'Bibli is verwijderd. De bibliotheekgegevens blijven bewaard in {0}'
      un_all = 'Bibli en al zijn gegevens zijn verwijderd.'
      cl_prompt = 'Naam of IP-adres van de Bibli-server (bv. BIBLIO-PC)'
      cl_done = 'Snelkoppeling « Bibli » op het bureaublad gemaakt. Opent {0}'
    }
    en = @{
      role_prompt  = 'How will this PC use Bibli?'
      role_app     = 'On this PC only (Bibli opens in its own window and stops with it)'
      role_server  = 'Server for several devices (always running, needs administrator rights)'
      role_client  = 'Another computer: a shortcut to the server installed elsewhere'
      elevated     = 'Windows asks for administrator rights; the install goes on in another window…'
      up_saved     = 'Copy of the database before the update: {0}'
      done_enter   = 'Done. Press Enter to close'
      press_enter  = 'Press Enter to close…'
      yes = 'yes'; no = 'no'
      pw_prompt    = 'Choose the library password (at least 12 characters; a phrase of three or four words works well). It will be asked to log in.'
      pw_tooshort  = 'At least 12 characters.'
      installing   = 'Installing Bibli to {0} (data in {1})…'
      cancelled    = 'Cancelled.'
      sum_running  = 'Bibli is installed and now starts every time the PC powers on.'
      sum_thispc   = '  On this PC           : {0}'
      sum_others   = '  Tablets, other PCs   : {0}'
      sum_icons1   = 'A "Bibli" icon on the Desktop, an icon in the notification area, and'
      sum_icons2   = 'a "Bibli (server)" menu in Start (start / stop / update).'
      sum_notup    = 'Bibli has not answered yet. See {0}'
      menu_folder  = 'Bibli (server)'
      svc_desc     = 'Library server (Bibli).'
      sc_open = 'Open Bibli'; sc_address = 'Address for tablets'; sc_status = 'Server status'
      sc_start = 'Start the server'; sc_stop = 'Stop the server'; sc_restart = 'Restart the server'
      sc_logs = 'View the log'; sc_data = 'Data folder'; sc_update = 'Update Bibli'; sc_uninstall = 'Uninstall Bibli'
      msg_started = 'Server started.'; msg_stopped = 'Server stopped.'; msg_restarted = 'Server restarted.'
      lbl_task = 'Service:'; lbl_responds = 'Answers on the network:'; lbl_address = 'Address:'
      addr_intro = 'On the tablets and the other computers, open:'
      t_hide = 'Hide the icon (the server keeps running)'
      tip_up = 'Bibli — running'; tip_down = 'Bibli — stopped'
      up_title = 'Choose the newly downloaded Bibli (.exe)'
      un_kept = 'Bibli has been removed. The library data is kept in {0}'
      un_all = 'Bibli and all its data have been removed.'
      cl_prompt = 'Name or IP address of the Bibli server (e.g. BIBLIO-PC)'
      cl_done = '"Bibli" shortcut created on the Desktop. It opens {0}'
    }
  }
  return $all[$lang]
}
